In [1]:
# 导入NumPy库，并将其重命名为np，方便后续使用
import numpy as np
# 导入time模块，用于测量代码执行时间
import time

# 创建一个包含1000000个元素的Python列表，元素从0到999999
python_list = list(range(1000000))

# 创建一个包含1000000个元素的NumPy数组，元素从0到999999
numpy_array = np.arange(1000000)

# 记录Python列表平方运算开始时间
start_time_list = time.time()
# 使用列表推导式计算Python列表中每个元素的平方
squared_list = [i ** 2 for i in python_list]
# 记录Python列表平方运算结束时间
end_time_list = time.time()
# 计算Python列表平方运算所花费的时间
list_time = end_time_list - start_time_list

# 记录NumPy数组平方运算开始时间
start_time_numpy = time.time()
# 对NumPy数组中的每个元素进行平方运算
squared_numpy = numpy_array ** 2
# 记录NumPy数组平方运算结束时间
end_time_numpy = time.time()
# 计算NumPy数组平方运算所花费的时间
numpy_time = end_time_numpy - start_time_numpy

# 打印Python列表平方运算所花费的时间
print(f"Python列表平方运算耗时: {list_time} 秒")
# 打印NumPy数组平方运算所花费的时间
print(f"NumPy数组平方运算耗时: {numpy_time} 秒")
# 打印NumPy数组相对于Python列表快的倍数
print(f"NumPy数组比Python列表快 {list_time / numpy_time} 倍")


Python列表平方运算耗时: 0.032610416412353516 秒
NumPy数组平方运算耗时: 0.0009875297546386719 秒
NumPy数组比Python列表快 33.02221149203283 倍


# 4 NumPy 的Ndarray 对象

In [ ]:
list1 = [1,2,3,4]
oneArray = np.array(list1) 
print(type(oneArray))
print(oneArray) #输出结果之间是没有逗号

<class 'numpy.ndarray'>
[1 2 3 4]


In [ ]:
# 2. 传入range生成序列
t2 = np.array(range(10)) 
print(t2)
type(t2)  #默认最后一个位置会输出，前面的变量要输出要加print

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [6]:
#  3. 使用numpy自带的np.arange()生成数组
t3 = np.arange(0,10,2) 
print(t3) 

[0 2 4 6 8]


In [ ]:
list2 = [[1,2],[3,4],[5,6]]

twoArray = np.array(list2)
# 显示数组的形状
print("数组的形状:", twoArray.shape)
# 显示数组的维度
print("数组的维度:", twoArray.ndim)
# 显示数组中元素的总数
print("数组中元素的总数:", twoArray.size)
# 显示数组中元素的数据类型，ndarray的整数不是无穷大
print("数组中元素的数据类型:", twoArray.dtype)
# 显示数组每个元素的字节大小
print("数组每个元素的字节大小:", twoArray.itemsize)



数组的形状: (3, 2)
数组的维度: 2
数组中元素的总数: 6
数组中元素的数据类型: int32
数组每个元素的字节大小: 4


In [10]:
#改变数组形状
four = np.array([[1,2,3],[4,5,6]])

# 修改的是原有的
four.shape = (3,2) 
print(four)

# 返回一个新的数组
five = four.reshape(2,3) 
print(five)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 将多维变成一维数组
five = four.reshape((6,),order='C')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten(order='C') 
print(five)
print(six)

[1 3 5 2 4 6]
[1 2 3 4 5 6]


In [ ]:
seven=six.reshape(3,2) #当你把一个数组改变形状到低维后，再次回到高维，元素的位置和最初是 一致的
print(seven)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
t = np.arange(24) 
print(t)
print(t.shape)
print(type(t.shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
<class 'tuple'>


In [18]:
# 转换成二维
t1 = t.reshape((4,6)) 
print(t1)
print(t1.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [20]:
t = np.arange(6) 
print(t)
print(t.shape)
t1=t.reshape((1,6))
print(t1)
print(t1.shape)


[0 1 2 3 4 5]
(6,)
[[0 1 2 3 4 5]]
(1, 6)


In [21]:
# 将数组转成list
a= np.array([9, 12, 88, 14, 25])
list_a = a.tolist() 
print(list_a) 
print(type(list_a))

[9, 12, 88, 14, 25]
<class 'list'>


# 5 数据类型

In [2]:
import numpy as np
import random
# 返回数组中每个元素的字节单位长度，dtype设置数据类型
f = np.array([1,2,3,4,5], dtype = np.int16) 
print(f.itemsize) # 
# 获取数据类型
print(f.dtype)

# 调整数据类型
f1 = f.astype(np.int64) 
print(f1.dtype)

# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(),2))

arr = np.array([random.random() for i in range(10)]) #默认是float64
print(arr)
# 取小数点后两位,四舍五入
print(np.round(arr,2))
arr.dtype

2
int16
int64
0.54
[0.29100748 0.10999504 0.9742345  0.79910943 0.11798756 0.94172756
 0.08112061 0.23144215 0.5036637  0.3966648 ]
[0.29 0.11 0.97 0.8  0.12 0.94 0.08 0.23 0.5  0.4 ]


dtype('float64')

# 6 数组的计算

In [27]:
t1 =np.arange(24).reshape((6,4)) 
print(t1+2)
print("-"*20)
print(t1*2) 
print("-"*20)
print(t1/2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [ ]:
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))

print(t1+t2) 
print('-'*50) 
print(t1-t2)

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]]


In [ ]:
#当尺寸不同时，要求其中一个轴的size为1
t1 = np.arange(24).reshape((4,6)) 
t2 = np.arange(6).reshape((1,6)) 
print(t1)
print('-'*50) 
print(t2) 
print('-'*50) 
print(t1-t2) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[0 1 2 3 4 5]]
--------------------------------------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [34]:

t1 = np.arange(24).reshape((4,6)) 
t2 = np.arange(6)
print(t2)
print(t1-t2)

[0 1 2 3 4 5]
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [36]:
t1 = np.arange(24).reshape((4,6)) 
t2 = np.arange(4).reshape((4,1))
print(t1)
print('-'*50) 
print(t2) 
print('-'*50) 
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[0]
 [1]
 [2]
 [3]]
--------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [ ]:
# 数组中轴，很重要
#按什么轴运算，什么轴变化,非常重要
a = np.array([[1,2,3],[4,5,6]]) #shape(2,3)
print(np.sum(a,axis=0)) # [5 7 9]
print("-"*20)
print(np.sum(a,axis = 1)) # [ 6 15]
print("-"*20)
print(np.sum(a)) #整体求和
print("-"*20)
a=np.arange(24).reshape((2,3,4))
print(a)

b=np.sum(a, axis=0)
print("-"*20)
print(b)
print(b.shape)
c=np.sum(a, axis=1)
print("-"*20)
print(c)
print(c.shape)
d=np.sum(a, axis=2)
print("-"*20)
print(d)
print(d.shape)

[5 7 9]
--------------------
[ 6 15]
--------------------
21
--------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
(3, 4)
--------------------
[[12 15 18 21]
 [48 51 54 57]]
(2, 4)
--------------------
[[ 6 22 38]
 [54 70 86]]
(2, 3)


# 7 数组的索引与切片

In [1]:
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print('取连续的多行\n',t1[1:])
print('*'*20)
print('取连续的多行\n',t1[1:3,:])
print('*'*20)
print('取不连续的多行\n',t1[[0,2,3]])#
print('*'*20)
print('取不连续的多行\n',t1[[0,2,3],:])
print('*'*20)
print('取一列\n',t1[:,1])
print('*'*20)
print('连续的多列\n',t1[:,1:])
print('*'*20)
print('取不连续的多列\n',t1[:,[0,2,3]])
print('*'*20)
print('取某一个值,三行四列\n',t1[2,3])
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
取连续的多行
 [[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
取连续的多行
 [[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
取不连续的多行
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
取不连续的多行
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
取一列
 [ 1  7 13 19]
********************
连续的多列
 [[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
取不连续的多列
 [[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
取某一个值,三行四列
 15
********************


In [ ]:
t1[[1,2],[1,4]] #1,1是7     2,4是16

array([ 7, 16])

In [44]:
t1[1:3,1:5]

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16]])

# 8 数组中的数值修改

In [47]:
t = np.arange( 24 ).reshape( 4, 6 )

# # 修改某一行的值
# t[1, :] = 0
#
# # 修改某一列的值
# t[:, 1] = 0
# #
# # # 修改连续多行
# t[1:3, :] = 0
# #
# # # 修改连续多列
# t[:, 1:4] = 0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
t[[0,1],[1,3]]=0
t


array([[ 0,  0,  2,  3,  4,  5],
       [ 6,  7,  8,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [50]:
t = np.arange( 24 ).reshape( 4, 6 )
t<2

array([[ True,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [ ]:
t = np.arange( 24 ).reshape( 4, 6 )
# 可以根据条件修改，比如讲小于10的值改掉
# t[t < 10] = 0
# print(t)
# 使用逻辑判断
# np.logical_and   & # np.logical_or  |
# np.logical_not      ~
# t[(t > 2) & (t < 6)] = 0  # 与
# t[(t < 2) | (t > 6)] = 0  # 或
# t[~(t > 6)] = 0  # 非
# # print(t)
t=t.clip(10,18)
# print(t)

# # # 拓 展

t

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 18, 18, 18, 18, 18]])

In [53]:
# # # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where( score > 80, True, False )
print( result )

[[False  True]
 [ True  True]
 [False  True]]


# 9 数组的添加、删除和去重

In [54]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')

print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')

print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [55]:
a = np.array([[1, 2], [3, 4], [5, 6]])

print('第一个数组：')
print(a)
print('\n')

print('常见场景')
print(np.insert(a, 1, [11, 12],axis=0))

print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 3, [11, 12]))
print('\n')
print('传递了 Axis 参数。 会广播值数组来配输入数组。')

print('沿轴  0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')

print('沿轴  1 广播：')
print(np.insert(a, 1, 11, axis=1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


常见场景
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]
未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴  0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴  1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [56]:
#数组的删除
a = np.arange(12).reshape(3,4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a,5))
print('\n')

print('删除每一行中的第二列：')
print(np.delete(a,1,axis = 1))
print('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




In [ ]:
#去重
a = np.array([5,2,6,2,7,5,6,8,2,9])

print ('第一个数组：')
print (a)
print ('\n')

print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')

print ('去重数组的索引数组：往下的都不重要')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')

print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')

print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]
去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


# 10 numpy的数学计算

In [59]:
score = np.array([[80,88],[82,81],[75,81]])
# 1. 获取所有数据最大值
result = np.max(score)
print(result)
# 2. 获取某一个轴上的数据最大值
result = np.max(score,axis=0)
print(result)
# 3. 获取最小值
result = np.min(score)
print(result)
# 4. 获取某一个轴上的数据最小值
result = np.min(score,axis=1)
print(result)


88
[82 88]
75
[80 81 75]


In [62]:
# 5. 数据的比较
result = np.maximum( [-2, -1, 0, 1, 2], 0 )  # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum( [-2, -1, 0, 1, 2], 0 )  # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum( [-2, -1, 0, 1, 2], [-10, 2, 3, 4, 5] )
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；

# 6. 求平均值
result = np.mean(score) # 获取所有数据的平均值
print(result)
result = np.mean(score,axis=0) # 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr    = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(axis=0))
'''
[1, 2, 3]------>   |1 |2 |3 |
[4, 5, 6]------>   |5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(1))
'''
[1, 2, 3]------>   |1 |2+1   |3+2+1 |
[4, 5, 6]------>   |4 |4+5   |4+5+6 |
'''



[0 0 0 1 2]
[-2 -1  0  0  0]
[-2  2  3  4  5]
81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


'\n[1, 2, 3]------>   |1 |2+1   |3+2+1 |\n[4, 5, 6]------>   |4 |4+5   |4+5+6 |\n'

In [64]:
score

array([[80, 88],
       [82, 81],
       [75, 81]])

In [63]:
# 8. argmin求最小值索引
result = np.argmin(score,axis=0)
res=np.min(score,axis=0) #这样我们就可以知道最小的81是第二排的，是从前往后遍历的
print(result,res)

# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score,axis=0)
print(result)

# 10. 极 值
result = np.ptp(score,axis=None)#就是最大值和最小值的差
print(result)

[2 1] [75 81]
[2.94392029 3.29983165]
13


# 11 拼接与分割

In [7]:
import numpy as np
# 按轴连接 concatenate
arr = np.arange(12).reshape(4,3)
print('原始数组：\n',arr)

# 按纵轴连接
print('按纵轴连接：\n',np.concatenate((arr, [[9, 9, 6], [0, 0, 7]] ), axis=0))

print('按横轴连接：\n',np.concatenate((arr, [[8],[8],[8],[8]] ), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


In [11]:
# 按轴堆叠
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print('按纵轴堆叠：\n', np.stack((a,b) ,axis=0 ))     # 把把数组b作为整体，堆叠到数组a的纵轴上，升维

print('按横轴堆叠：\n', np.stack((a,b) ,axis=1 ))     # 把a数组的 [1,2] 和 b数组的 [5,6] 堆叠到一起，作为一个整体，升维

沿轴 0 连接两个数组：
(3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


沿轴 1 连接两个数组：
(2, 3, 2)
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]


In [13]:
arr = np.arange(12).reshape(3,4)
print('原始数组：\n',arr)

# 将数组三等分，默认按纵轴分
print('纵轴等分后的数组：\n', np.split(arr,3))

# 设置切割点，先按第一行切割，再按第一列切割
# print('纵轴切割后的数组：\n', np.split(arr,[1,1]))

# 将数组按横轴等分
print('横轴等分后的数组：\n', np.split(arr,4,axis=1))

将数组分为三个大小相等的子数组：
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
原array：
[[1. 7. 2. 6. 8. 7.]
 [3. 8. 4. 8. 1. 0.]]
拆分后：
[array([[1., 7.],
       [3., 8.]]), array([[2., 6.],
       [4., 8.]]), array([[8., 7.],
       [1., 0.]])]
第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [16]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

# 12 数组中nan和inf

In [19]:
# 创建一个nan和inf #
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))

# --判断数组中为nan的个数
t = np.arange(24,dtype=float).reshape(4,6)

# 将三行四列的数改成nan
t[3,4] = np.nan
print(t)
# 可以使用np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t))
print(t!=t)
# 并 且  np.nan != np.nan    结果 是TRUE
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.count_nonzero(t != t))

nan <class 'float'>
inf <class 'float'>
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
23
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False  True False]]
1


In [20]:
# 将nan替换为0
t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [21]:
# ----------练习： 处理数组中nan
t = np.arange(24).reshape(4,6).astype('float')
#
# 将数组中的一部分替换nan
t[1,3:] = np.nan
print(t)
print('-------------------')

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------


In [23]:
t.shape[1]

6

In [24]:
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
   #获取当前列数据
   temp_col = t[:,i]

   # 判断当前列的数据中是否含有nan
   nan_num = np.count_nonzero(temp_col != temp_col)
   # 条件成立说明含有nan
   if nan_num != 0:
      # 将这一列不为nan的数据拿出来
      temp_col_not_nan = temp_col[temp_col == temp_col]
      
      # 将nan替换成这一列的平均值
      temp_col[np.isnan( temp_col )] = np.mean( temp_col_not_nan )
      
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


# 13  二维数组的转置，轴滚动

In [25]:
a = np.arange(12).reshape(3,4)
print ('原数组：')
print (a )
print ('\n')

print ('对换数组：')
print (np.transpose(a))

# 与transpose一致
a = np.arange(12).reshape(3,4)

print ('原数组：')
print (a)
print ('\n')

print ('转置数组：')
print (a.T)

# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4,6)
re = t1.swapaxes(1,0)
print (' 原 数 组 ：')
print (t1)
print ('\n')

print ('调用 swapaxes 函数后的数组：')
print (re)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [28]:
t=np.ones((2,3,4,5))
np.rollaxis(t,3,1).shape

(2, 5, 3, 4)