In [4]:
import numpy as np

# 创建 ndarray 对象（数组）

In [8]:
arr = np.array( range(10) )
# arr = np.array([1,2,3,4,5,6,7])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.arange( 0, 10 , 2)
# 从 0 到 10 左闭右开 间隔为 2 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##  高维数组

In [17]:
# 1、直接构造列表 ， 再array
list = [ [1,2] , [3,4] , [5,6] ]
arr = np.array( list )
print(arr)
print("*" * 60) 

# 2、先一维 再向高维 reshape
arr1 = np.arange(24).reshape(2,6,2)   # 2张 6行2列 的切片
print(arr1)

[[1 2]
 [3 4]
 [5 6]]
************************************************************
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]]]


# 属性  
shape-形状元组 &emsp;  reshape-改变形状  &emsp;  size-元素数  &emsp;  ndim-维数<br>
***reshape(1,6) ， 两个参数 ， 是一行六列的二维数组 ， 而不是一维数组***

# 数据类型    
dtype-设置数据类型  &emsp;  itemsize-元素字节大小  &emsp;  round-构造保留小数的数组<br>
* 不需要在创建时，设置数据类型的方法 ： arr.astype( 数据类型 )

In [129]:
arr = np.array([1,2,3,4,5],dtype=np.int8)
print(arr.itemsize)
print(arr.astype(np.float16).itemsize)

import random
arr = np.array([random.random() for _ in range(10)])
arr1 = np.round(arr,2)
print(arr1)

1
2
[0.56 0.28 0.99 0.17 0.5  0.92 0.37 0.26 0.11 0.53]


# 数组运算

In [42]:
# 相同形状的数组计算
arr1 = np.arange(12).reshape(2,6)
arr2 = np.arange(12,24).reshape(2,6)
print(arr1)
print(arr2)
print(arr1 + arr2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 14 16 18 20 22]
 [24 26 28 30 32 34]]


In [65]:
# 不同形状多维数组 --- 只能是数组+某一维向量
arr1 = np.arange(24).reshape(2,6,2)

arr2 = np.arange(2).reshape(2,1,1)
# np.arange(2).reshape(1,1,2)
# np.arange(6).reshape(1,1,6)
# np.arange(6).reshape(1,6,1)

print(arr1)
print(arr2)
print('*'*60)
print(arr1 + arr2)
# print(arr1+arr3)   Error!

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[0]]

 [[1]]]
************************************************************
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[13 14]
  [15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]]]


# 数组的轴
二维：0-纵轴  1-横轴<br>
三维：0-新轴  1-纵轴  2-横轴<br>
n维：0-新轴 1-上一个的新轴 ……<br>
**按什么轴运算，什么轴变化（非常重要）**

In [100]:
arr = np.arange(12).reshape(3,4)
print('原始数组：\n',arr)

print('纵轴求和：\n',np.sum( arr , axis=0 ))

print('横轴求和：\n',np.sum( arr , axis=1 ))

原始数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
纵轴求和：
 [12 15 18 21]
横轴求和：
 [ 6 22 38]


In [89]:
arr = np.arange(12).reshape(2,6)
print('原始数组：\n',arr)

print('不指定轴：\n',np.append( arr , [13,14,15,16,17,18]))

print('指定纵轴（改变纵轴）：\n',np.append(arr, [[-1, -2, -3, -4, -5, -6]], axis=0))   
# np.append(arr, [-1, -2, -3, -4, -5, -6], axis=0)   报错，必须保证插入的数组和arr维数相同

print('指定横轴（改变横轴）：\n',np.append(arr, [[-1, -2, -3], [-4, -5, -6]], axis=1))

原始数组：
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
不指定轴：
 [ 0  1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18]
指定纵轴（改变纵轴）：
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [-1 -2 -3 -4 -5 -6]]
指定横轴（改变横轴）：
 [[ 0  1  2  3  4  5 -1 -2 -3]
 [ 6  7  8  9 10 11 -4 -5 -6]]


In [91]:
arr = np.arange(12).reshape(2,6)
print('原始数组：\n',arr)

print('不指定轴：\n',np.insert( arr , 1 , [13,14] ))

print('指定纵轴（改变纵轴）：\n',np.insert(arr, 1 , [-1, -2, -3, -4, -5, -6], axis=0))

print('指定横轴（改变横轴）：\n',np.insert(arr, 6 , [99], axis=1))  # 广播

原始数组：
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
不指定轴：
 [ 0 13 14  1  2  3  4  5  6  7  8  9 10 11]
指定纵轴（改变纵轴）：
 [[ 0  1  2  3  4  5]
 [-1 -2 -3 -4 -5 -6]
 [ 6  7  8  9 10 11]]
指定横轴（改变横轴）：
 [[ 0  1  2  3  4  5 99]
 [ 6  7  8  9 10 11 99]]


In [99]:
arr = arr = np.arange(12).reshape(2,6)
print('原始数组：\n',arr)

print('不指定轴：\n',np.delete( arr , 0 ))

print('指定纵轴（改变纵轴）：\n',np.delete(arr, 1 , axis=0))

print('指定横轴（改变横轴）：\n',np.delete(arr, 0 , axis=1))

原始数组：
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
不指定轴：
 [ 1  2  3  4  5  6  7  8  9 10 11]
指定纵轴（改变纵轴）：
 [[0 1 2 3 4 5]]
指定横轴（改变横轴）：
 [[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


# 索引和切片

In [102]:
arr = np.arange(24).reshape(4,6)
print('原始数组：\n',arr)
print('取1-2行：\n',arr[1:3])  
print('取0,2,3行：\n',arr[[0,2,3]])

print('取(0,1),(2,3)：\n',arr[ [0,2] , [1,3] ])
print('取2-3行，3-4列的元素：\n',arr[ 2:4 , 3:5 ])

原始数组：
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
取1-2行：
 [[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
取0,2,3行：
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
取(0,1),(2,3)：
 [ 1 15]
取2-3行，3-4列的元素：
 [[15 16]
 [21 22]]


# 数据修改和比较

In [113]:
arr = np.arange( 24 ).reshape( 4, 6 )

# 所有符合 <2 的元素 ，都返回 True
arr<10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [114]:
arr = np.arange(24).reshape(4,6)

arr[ (arr<10) | (arr>20) ] = -1
print('把小于10，大于20的元素修改为-1：\n',arr)

arr = arr.astype(float)     # non是浮点数，需要把数组变成浮点数组
arr[ arr==-1] = np.nan
print('把-1改成nan：\n',arr)

arr[ np.isnan(arr) ] = 0
print('把nan改成0：\n',arr)


把小于10，大于20的元素修改为-1：
 [[-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 10 11]
 [12 13 14 15 16 17]
 [18 19 20 -1 -1 -1]]
把-1改成nan：
 [[nan nan nan nan nan nan]
 [nan nan nan nan 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. nan nan nan]]
把nan改成0：
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20.  0.  0.  0.]]


# nan 和 inf

In [145]:
arr = np.arange(12,dtype=float).reshape(3,4)
non = np.nan
arr[ arr<5 ] = non
print(arr)

print('*'*60)
print('接下来演示non和non是否相等,arr==arr?：')
print(arr==arr)

print('*'*60)
arr[np.isnan(arr)]=-1
print('演示 nan!=nan 和 np.isnan( ) 是等价的：\n',arr)


[[nan nan nan nan]
 [nan  5.  6.  7.]
 [ 8.  9. 10. 11.]]
************************************************************
接下来演示non和non是否相等,arr==arr?：
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
************************************************************
演示 nan!=nan 和 np.isnan 是等价的：
 [[-1. -1. -1. -1.]
 [-1.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
