In [1]:
import numpy as np

# 数组的连接、分割、堆叠与去重

In [8]:
# 按轴连接 concatenate
arr = np.arange(12).reshape(4,3)
print('原始数组：\n',arr)

# 按纵轴连接
print('按纵轴连接：\n',np.concatenate((arr, [[9, 9, 6], [0, 0, 7]] ), axis=0))

print('按横轴连接：\n',np.concatenate((arr, [[8],[8],[8],[8]] ), axis=1))

原始数组：
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
按纵轴连接：
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 9  9  6]
 [ 0  0  7]]
按横轴连接：
 [[ 0  1  2  8]
 [ 3  4  5  8]
 [ 6  7  8  8]
 [ 9 10 11  8]]


In [12]:
# 按轴堆叠
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print('按纵轴堆叠：\n', np.stack((a,b) ,axis=0 ))     # 把把数组b作为整体，堆叠到数组a的纵轴上，升维

print('按横轴堆叠：\n', np.stack((a,b) ,axis=1 ))     # 把a数组的 [1,2] 和 b数组的 [5,6] 堆叠到一起，作为一个整体，升维

按纵轴堆叠：
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
按横轴堆叠：
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [21]:
arr = np.arange(12).reshape(3,4)
print('原始数组：\n',arr)

# 将数组三等分，默认按纵轴分
print('纵轴等分后的数组：\n', np.split(arr,3))

# 设置切割点，先按第一行切割，再按第一列切割
# print('纵轴切割后的数组：\n', np.split(arr,[1,1]))

# 将数组按横轴等分
print('横轴等分后的数组：\n', np.split(arr,4,axis=1))


原始数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
纵轴等分后的数组：
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
纵轴切割后的数组：
 [array([[0, 1, 2, 3]]), array([], shape=(0, 4), dtype=int32), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])]
横轴等分后的数组：
 [array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
